# Global CryptoCurrency (GCC)
Our mission is to change the way people buy and produce every day goods and services. By decentralising production, logistics and payments, we will contribute to the environment and people.
## Proof-of-stake (PoS)
Global cryptocurrency (GCC) is a free open source project. Our Proof-of-stake is based on coin age and generated by each node via a hashing scheme bearing similarity to Bitcoin’s but over limited search space. Block chain history and transaction settlement are further protected by a centrally broadcasted checkpoint mechanism. 

PoS rewards based on year (MAX):
* 20 % until 10.04.2018 annually 
* 18 % until 10.04.2019 annually 
* 16 % until 10.04.2020 annually 
* 14 % until 10.04.2021 annually 
* 12 % until 10.04.2022 annually
< 2% annually

PoS furthure explanation: [link](http://earlz.net/tags/altcoins/1)

### Setup

Unpack the files into a directory and run:


```
 bin/32/TheGCCcoind (headless, 32-bit)
 bin/64/TheGCCcoind (headless, 64-bit)
```

The software automatically finds other nodes to connect to.  You can
enable Universal Plug and Play (UPnP) with your router/firewall
or forward port 36502 (TCP) to your computer so you can receive
incoming connections.  GCC works without incoming connections,
but allowing incoming connections helps the GCC network.

### Upgrade

```
All you existing coins/transactions should be intact with the upgrade.
To upgrade first backup wallet
TheGCCcoind backupwallet <destination_backup_file>
Then shutdown TheGCCcoind by
TheGCCcoind stop
Start up the new TheGCCcoind.
```

## Acknowledgments

* https://bitcointalk.org/index.php?topic=2208174.0
* https://t.me/GCCglobalcryptocurrency
* https://medium.com/@thegcccoin/
* https://www.thegcccoin.com/
* https://en.m.bitcoinwiki.org/wiki/TheGCCcoin

## Contributing

Please read fallow rules which are listed [here](https://gist.github.com/PurpleBooth/b24679402957c63ec426) for details on our code of conduct, and the process for submitting pull requests to us.
